### ISSUE TITLE
archive vs trash

### ISSUE THREAD

**Issue by robertsawko** [capstayn/workstation_config#2]
How to simply differentiate between archiving messages and binning them entirely.

I'd like to return to the ideal of small inbox but large message archive.

**Comment by capstayn** [comment]
If I understand your question, to bin a message you use `d`. To archive it (move it to some folder) you use `s`. 
You can tag a number of e-mails (even by means of a regex) and then save them to a specific folder with `;` (see [here](https://stackoverflow.com/questions/9679914/how-to-move-multiple-messages-in-mutt))

**Comment by robertsawko** [comment]
Hmmm... I suppose all I need is a simple shortcut e.g. "a" to archive
things quickly. So that it can be combined with tagging. Then you can
quickly go through your messaged "d" the ones you never want to see
again and "a" the ones you want to come back at some point in the not
too distant future.

-- 
No deltas, no Cardanos, no hope...
http://en.wikipedia.org/wiki/Abel–Ruffini_theorem

**Comment by robertsawko** [comment]
Weird. I just discovered that my binning is actually archiving things...

**Comment by robertsawko** [comment]
Ok. I think I know what's happening. When mutt deletes a message from a mailbox it actually just (sensibly) deletes it from a mailbox rather than moving it to bin. From IMAP side this translates into removing a label. A label-less message on GMAIL sits in "Archive".

To stay consistent with this behavoiur it might be better to have a shorcut for deleting and binning ("b") which would translate into moving things to bin.

**Comment by robertsawko** [comment]
Ok. I found a [post](https://unix.stackexchange.com/questions/102829/mutt-save-message-to-specific-folder) which covers what I want but solution moving by cursor to the last entry in the current mailbox. Weird!

**Comment by robertsawko** [comment]
Apparently, the trashing is one of the [features](https://neomutt.org/feature/trash) of neomutt.

**Comment by robertsawko** [comment]
[This](https://grantlucas.com/posts/2014/01/note-archiving-gmail-messages-mutt) appears to describe my issue!

**Comment by robertsawko** [comment]
Gosh this is complicated. There's IMAP and there's IMAP+Google POWER... Good giref...

After some hacking. I think I am happy with the following setup which is gmail specific:
```
set trash = "+[Gmail]/Trash"
bind index D purge-message
macro index,pager a "<save-message>+[Gmail]/All Mail<enter>" "Archive a message"
```
So I use neomutt feature trashing mail and archiving with a special macro. I use tagging `t` copled with `;<d|D|a>` to respectively trash, purge (remove completely; bypassing bin), archive.
