### ISSUE TITLE
A hook for responding to portal APIs

### ISSUE THREAD

**Issue by robertsawko** [capstayn/workstation_config#4]
Some websites, such as GH send you emails to which you can respond inside your email and the reply will appear on the website. I'd like to have a different VIM settings when I respond to these messages as for instance

- fixed line width doesn't render,
- my signature is redundant or even annoying perhaps

**Comment by capstayn** [comment]
I would say [here](https://neomutt.org/guide/configuration.html#send-hook) you will find what you are looking for. 

Basically, your `reply-hook`will be something of this sort: 

``
reply-hook notifications@github.com 'set signature="" ' 'source .specific_vim_format'
``

Let me know if this helps, Apparently mutt is [especially good](https://www.techrepublic.com/blog/linux-and-open-source/my-number-one-reason-to-use-mutt-managing-multiple-profiles/) for this.

**Comment by robertsawko** [comment]
Thanks. That's looking quite promising.

**Comment by robertsawko** [comment]
Ok. So that doesn't work on its own. Because if I respond to GH message then the signature is unset globally. Somehow needs to be local to the message.

**Comment by robertsawko** [comment]
I left a [question](https://unix.stackexchange.com/questions/585744/can-mutt-automatically-format-a-message-for-responding-to-notifications) on Unix stackoverflow and got a brilliant reply. This works as expected although I need to fine tune my vim settings now. I am going to keep it open until I sort out these vim specific settings (e.g. now line wrapping).

**Comment by robertsawko** [comment]
I went with variables route:
```
set my_editor="nvim"
set my_vim_email_options="-c 'set syntax=mail fileencoding=utf-8 ft=mail fo+=aw'"
set my_vim_github_options="-c 'set wrap textwidth=0'"
...
reply-hook ~A \
    'set signature="fortune ~/.mutt/signatures|";\
    set editor="$my_editor $my_vim_email_options"'

# This hook applies only to those matching notifications@github.com
reply-hook notifications@github.com \
    'set signature="";\
    set editor="$my_editor $my_vim_github_options"'
