### ISSUE TITLE
gmail recording of sent messages

### ISSUE THREAD

**Issue by robertsawko** [capstayn/workstation_config#5]
I think gmail automatically adds any outgoing messages to "Sent". This means that the the `record` variable needs to be unset as the message will appear twice there - once added by gmail server and once by mutt.

Is that your understanding too?

**Comment by capstayn** [comment]
I just checked it out and yes, you are right. My emails were been duplicate in the Sent mailbox. The same was happening with the outlook account. 
Fixed at 3724eb3f145e0dae02bfdd4982598adb727acb7e

**Comment by robertsawko** [comment]
I think @capstayn you should actually use 

`unset record` just in case any of your other email accounts in the future needs to set it.

**Comment by capstayn** [comment]
Yes, thanks. 

Fixed at 25b811652242c3b4e244f8775e2bc6754715ab68
