### ISSUE TITLE
How do you handle multiple remote servers?

### ISSUE THREAD

**Issue by robertsawko** [capstayn/workstation_config#6]
I am interested what you're doing for multiple remote servers? For local copy I used to use hooks to change some parameters, but you need to now sync with multiple imap servers to update sidebar for instance. I wonder how you do it.

I'd like to have the following structure
```
.mutt         
├── accounts
│   ├── gmail
│   │   ├── muttrc
│   │   ├── hook???
│   │   └── tokens.gpg
│   └── stfc
│       ├── muttrc
│       ├── hook???
│       └── password.gpg
...
```
where `muttrc` sitting inside the directory named after an account is specific mutt setting for this account. It might be that we require `muttrc` and `hook` file which will be executed when we move to one of the mailboxes associated with this account, but I am not sure what is the best at this stage.

Let me know.

**Comment by robertsawko** [comment]
@capstayn you're doing this:
```
## Eurecat
folder-hook $my_hostname_work 'source ~/.neomutt/workrc'
## gmail
folder-hook $my_hostname_gmail 'source ~/.neomutt/gmailrc'

# The last sourced will be the first in appear on neomutt
source ~/.neomutt/gmailrc
source ~/.neomutt/workrc

## macros
# switch to different accounts
#macro index <f2> '<change-folder>imaps://imap.gmail.com<enter>'
#macro index <f3> '<change-folder>imaps://imap.eurecat.org<enter>'
macro index <f2> '<sync-mailbox><enter-command>source ~/.neomutt/gmailrc<enter><change-folder>!<enter>'
macro index <f3> '<sync-mailbox><enter-command>source ~/.neomutt/workrc<enter><change-folder>!<enter>'
```

But I find it a little surprising as you overwrite the settings on the initialisation and does it really work after you started the client? For instance will get updated the moment Eurecat mailbox receives new messages if you're logged in to google? I wonder.

**Comment by robertsawko** [comment]
I just think there needs to be a separate file setting the global setting and logging you into the server and a separate file for the hook. Let me know if you have any thoughts on this.

**Comment by capstayn** [comment]
> But I find it a little surprising as you overwrite the settings on the initialisation and does it really work after you started the client? 

Yes, I'm doing this and a specific hook at the end of of each account_rc file: 

``
account-hook gmail.com 'set imap_user=$imap_user imap_pass=$imap_pass'
``

likewise for the work account. I does work, although now I realise there is no need to source both accounts.  

> For instance will get updated the moment Eurecat mailbox receives new messages if you're logged in to google? I wonder.

No, you only can see one inbox at a time. So if you want to check up new messages in an account, you need to switch to that account (with `f2` and `f3`). You refresh the sidebar with [`unmailboxes *`](https://github.com/capstayn/workstation_config/blob/3724eb3f145e0dae02bfdd4982598adb727acb7e/neomutt/gmailrc#L4)

> I just think there needs to be a separate file setting the global setting and logging you into the server and a separate file for the hook. Let me know if you have any thoughts on this.

That's roughly my idea, with the exception that the folder-hooks are in the global file. The passwords are loaded altogether, so that I only have to fill in the password to pgp once. If I am not mistaken, the difference between your file tree and mine would be almost cosmetic.

**Comment by robertsawko** [comment]
I completely don't understand `unmailboxes`. From the neomutt website:

>The “unmailboxes” command is used to remove a token from the list of folders which receive mail. “unmailboxes” can be used on the mailbox path, “$folder”-abbreviated path, or description. Use “unmailboxes *” to remove all tokens.

Yes, you're right - I am suggesting a cosmetic improvement with the directory structure - I have a bee in the bonnet about good directory naming.

But the more important thing is refreshing sidebar on the fly. I am wondering if it's possible to remain logged into multiple servers at once and keep refreshing mailboxes.

In this case hook would contain the minimal changes that you would expect when browsing a mailbox from a given server. So for instance if I am responding to an email in work mailbox I get my work signature and `from` but when I am in personal email I get my signatures.

**Comment by capstayn** [comment]
My understanding is that `unmailboxes` removes the specified mailbox (folder) from those that you can work with. If you don't 'unmailbox' an account before switching to the other, then you will see on the side bar (or the list of folders to work with, for that matter) folders from both accounts merged. 

> In this case hook would contain the minimal changes that you would expect when browsing a mailbox from a given server. So for instance if I am responding to an email in work mailbox I get my work signature and from but when I am in personal email I get my signatures.

Well, you can achieve this with the link I posted on #4 . I actually thought of the possibility of doing that, but I am happy with having to switch between accounts - I am a strong defender of a thick separation between work and (personal) life.

**Comment by capstayn** [comment]
> But the more important thing is refreshing sidebar on the fly. I am wondering if it's possible to remain logged into multiple servers at once and keep refreshing mailboxes.

Actually, you could do this easily with a macro

**Comment by robertsawko** [comment]
I don't believe that the macro would do. I foresee many problems. You're responding to a message for instance and suddenly the accounts change in the background. There needs to be a support for this in the client and it also needs to be asynchronous. In the offline version that would have worked because the interrogating the server for incoming email is separated from the client and the folder specific hooks are only to change things related to your identity...

But I think I could buy into your separation of concerns argument. I also hate being distracted by personal emails when I work and vice versa, so maybe that's the way to proceed.
